# Сбор данных о ВЭД Российской Федерации.

С 2022-ого года РФ не публикует детализированную статистику о своей внешнеэкономической деятельности. Целью данного проекта является ее зеркальное восстановление с помощью парсинга таможенных баз данных ключевых стран-партнеров и дальнейшего моделирования остатка. На данный момент парсер поддерживает сбор данных 62 стран-партнеров. Покрытие экспорта РФ составляет 85%, импорта - 75%.

Реализованные парсеры по странам:

1. Бразилия;
2. Республика Корея;
3. Япония;
4. Казахстан;
5. Гонгконг;
6. Тайвань;
7. Китай;
8. Индия;
9. Тайланд;
10. США;
11. Мексика;
12. Европа (44 страны - подробнее в отедльной секции 'Европа')
13. Вьетнам;
14. Армения;
15. Азербайджан;
16. Узбекистан;
17. Киргизия;
18. Таджикистан;
19. Беларусь;

Всего - 62 страны

### Обновление, чтение БД

Вспомогательный блок функций для подключения к базе и обработке спаршенных данных под структуру базы

In [36]:
import duckdb
import pandas as pd

europe_non_eu = [
    'Switzerland (incl. Liechtenstein ''LI'' -> 1994)',
    'Norway (incl. Svalbard and Jan Mayen ''SJ'' -> 1994 and again from 1997)',
    'Serbia',
    'North Macedonia',
    'Montenegro',
    'Kosovo',
    'Iceland',
    'Bosnia and Herzegovina',
    'Albania',
    'United Kingdom (Northern Ireland)',
    'Ukraine',
    'Moldova, Republic of',
    'Беларусь',
    'Georgia',
    'United Kingdom'
]

asia = [
    'Тайвань',
    'Таиланд',
    'Республика Корея',
    'Китай',
    'Вьетнам',
    'Узбекистан',
    'Киргизия',
    'Казахстан',
    'Индия',
    'Гонконг',
    'Армения',
    'Таджикистан',
    'Азербайджан'
]

america = [
    'Бразилия',
    'CША',
    'Мексика',
    'Эквадор'
]

middle_east = [
    "Türkiye"
]

eu_27 = [
    'Sweden',
    'Spain (incl. Canary Islands ''XB'' from 1997)',
    'Slovenia',
    'Slovakia',
    'Romania',
    'Portugal',
    'Poland',
    'Malta',
    'Netherlands',
    'Luxembourg',
    'Lithuania',
    'Latvia',
    'Italy (incl. San Marino ''SM'' -> 1993)',
    'Ireland (Eire)',
    'Hungary',
    'Greece',
    'Germany (incl. German Democratic Republic ''DD'' from 1991)',
    'France (incl. Saint Barthélemy ''BL'' -> 2012; incl. French Guiana ''GF'', Guadeloupe ''GP'', Martinique ''MQ'', Réunion ''RE'' from 1997; incl. Mayotte ''YT'' from 2014)',
    'Finland',
    'Estonia',
    'Denmark',
    'Czechia',
    'Cyprus',
    'Croatia',
    'Bulgaria',
    'Belgium (incl. Luxembourg ''LU'' -> 1998)',
    'Austria'
]

nato = [
    'Sweden',
    'Slovenia',
    'Slovakia',
    'Romania',
    'Portugal',
    'Poland',
    'Norway (incl. Svalbard and Jan Mayen ''SJ'' -> 1994 and again from 1997)',
    'Netherlands',
    'Luxembourg',
    'Latvia',
    'North Macedonia',
    'Italy (incl. San Marino ''SM'' -> 1993)',
    'Iceland',
    'Hungary',
    'Greece',
    'Germany (incl. German Democratic Republic ''DD'' from 1991)',
    'France (incl. Saint Barthélemy ''BL'' -> 2012; incl. French Guiana ''GF'', Guadeloupe ''GP'', Martinique ''MQ'', Réunion ''RE'' from 1997; incl. Mayotte ''YT'' from 2014)',
    'Finland',
    'Estonia',
    'Denmark',
    'Czechia',
    'Croatia',
    'Bulgaria',
    'Belgium (incl. Luxembourg ''LU'' -> 1998)',
    'Albania',
    'United Kingdom (Northern Ireland)',
    'CША',
    'United Kingdom',
    'Türkiye'
]

unfriendly = [
    'Sweden',
    'Spain (incl. Canary Islands ''XB'' from 1997)',
    'Slovenia',
    'Slovakia',
    'Romania',
    'Portugal',
    'Poland',
    'Malta',
    'Netherlands',
    'Luxembourg',
    'Lithuania',
    'Latvia',
    'Italy (incl. San Marino ''SM'' -> 1993)',
    'Ireland (Eire)',
    'Hungary',
    'Greece',
    'Germany (incl. German Democratic Republic ''DD'' from 1991)',
    'France (incl. Saint Barthélemy ''BL'' -> 2012; incl. French Guiana ''GF'', Guadeloupe ''GP'', Martinique ''MQ'', Réunion ''RE'' from 1997; incl. Mayotte ''YT'' from 2014)',
    'Finland',
    'Estonia',
    'Denmark',
    'Czechia',
    'Cyprus',
    'Croatia',
    'Bulgaria',
    'Belgium (incl. Luxembourg ''LU'' -> 1998)',
    'Austria',
    'Тайвань',
    'Республика Корея',
    'Япония',
    'Switzerland (incl. Liechtenstein ''LI'' -> 1994)',
    'Norway (incl. Svalbard and Jan Mayen ''SJ'' -> 1994 and again from 1997)',
    'North Macedonia',
    'Montenegro',
    'Iceland',
    'CША',
    'Albania',
    'United Kingdom (Northern Ireland)',
    'Ukraine',
    'United Kingdom'
]

brics = [
    'Бразилия',
    'Китай',
    'Индия'
]

sco = [
    'Китай',
    'Индия',
    'Казахстан',
    'Киргизия',
    'Таджикистан',
    'Узбекистан',
    'Беларусь'
]

cis = [
    'Казахстан',
    'Киргизия',
    'Узбекистан',
    'Таджикистан',
    'Армения',
    'Азербайджан',
    'Беларусь',
    'Moldova, Republic of',
    'Ukraine'
]

eaeu = [
    'Казахстан',
    'Киргизия',
    'Армения',
    'Беларусь'
]

def _connect_md(motherduck_token: str, db_name="my_db", schema="main"):
    con = duckdb.connect(
        f"md:{db_name}",
        config={"motherduck_token": motherduck_token}
    )
    con.execute(f"USE {db_name}.{schema}")
    return con

def prepare(data):
    data = data.copy()
    data["europe_non_eu"] = 0
    if 'Страна-партнер' in data.columns:
        data['Исходная страна'] = data['Страна-партнер']
    data.loc[data["Исходная страна"].isin([europe_non_eu]), "europe_non_eu"] = 1
    data["asia"] = 0
    data.loc[data["Исходная страна"].isin([asia]), "asia"] = 1
    data["america"] = 0
    data.loc[data["Исходная страна"].isin([america]), "america"] = 1
    data["middle_east"] = 0
    data.loc[data["Исходная страна"].isin([middle_east]), "middle_east"] = 1
    data["eu_27"] = 0
    data.loc[data["Исходная страна"].isin([eu_27]), "eu_27"] = 1
    data["nato"] = 0
    data.loc[data["Исходная страна"].isin([nato]), "nato"] = 1
    data["unfriendly"] = 0
    data.loc[data["Исходная страна"].isin([unfriendly]), "unfriendly"] = 1
    data["friendly"] = 0
    data.loc[data["unfriendly"] == 0, "friendly"] = 1
    data["brics"] = 0
    data.loc[data["Исходная страна"].isin([brics]), "brics"] = 1
    data["sco"] = 0
    data.loc[data["Исходная страна"].isin([sco]), "sco"] = 1
    data["cis"] = 0
    data.loc[data["Исходная страна"].isin([cis]), "cis"] = 1
    data["eaeu"] = 0
    data.loc[data["Исходная страна"].isin([eaeu]), "eaeu"] = 1
    data["africa"] = 0
    data["oceania"] = 0

    data["Направление"] = data["Направление"].replace({"Экспорт": "Импорт", "Импорт": "Экспорт"})
    if 'Единица стоимости' in data.columns:
        data["Единицы стоимости"] = data["Единица стоимости"]
    data["Страна-партнер"] = data["Исходная страна"]
    if 'Единица стоимости' in data.columns:
        data = data.drop(columns=["Исходная страна", "Единица стоимости"])
    else:
        data = data.drop(columns=["Исходная страна"])
    data["Отчетный период"] = pd.to_datetime(data["Отчетный период"], errors="coerce").dt.date

    return data

def update(con: duckdb.DuckDBPyConnection,
           data: pd.DataFrame,
           table: str = "trade_data",
           year: int = 2025):

    table_cols = [r[1] for r in con.execute(f"PRAGMA table_info('{table}')").fetchall()]
    data = data[table_cols]

    con.register("new_data", data)
    con.execute("BEGIN TRANSACTION;")
    try:
        con.execute(f"""
            DELETE FROM {table} t
            USING (SELECT DISTINCT "Страна-партнер" AS c FROM new_data) s
            WHERE t."Страна-партнер" = s.c
              AND EXTRACT(YEAR FROM t."Отчетный период") = ?;
        """, [year])

        cols_sql = ", ".join([f'"{c}"' for c in table_cols])
        con.execute(f"""
            INSERT INTO {table} ({cols_sql})
            SELECT {cols_sql} FROM new_data;
        """)

        con.execute("COMMIT;")
    except Exception:
        con.execute("ROLLBACK;")
        raise
    finally:
        con.unregister("new_data")

ЗАПИСЬ ДАННЫХ

In [ ]:
WRITE_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5kcmVldjEzQGdtYWlsLmNvbSIsIm1kUmVnaW9uIjoiYXdzLXVzLWVhc3QtMSIsInNlc3Npb24iOiJpdmFuZHJlZXYxMy5nbWFpbC5jb20iLCJwYXQiOiJYcHNZSGRsYjVpLXN0T1RjWFF3VkNUYUhXcFZBMk1Sa0hlbm04Y21wajRrIiwidXNlcklkIjoiNDA4NmNhZjItOTRiMC00NDJhLTk1NmEtNjEzZTkxYjM4NzJkIiwiaXNzIjoibWRfcGF0IiwicmVhZE9ubHkiOmZhbHNlLCJ0b2tlblR5cGUiOiJyZWFkX3dyaXRlIiwiaWF0IjoxNzY1OTgxMzgxfQ.yRi5vGrRLCg02L2QMYAQDpMXYuPJXqf-0jUn53ToYLs"
con = _connect_md(motherduck_token=WRITE_TOKEN)
update(con, prepare(data), table="trade_data", year=2025)
con.close()

ЧТЕНИЕ ДАННЫХ

In [ ]:
READ_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5kcmVldjEzQGdtYWlsLmNvbSIsInNlc3Npb24iOiJpdmFuZHJlZXYxMy5nbWFpbC5jb20iLCJwYXQiOiJtS3FreDdXeFZGdkFaNWVXbWFKR1pfQ2xocUg4TVNlVHM5Vi1raDJKRXpvIiwidXNlcklkIjoiNDA4NmNhZjItOTRiMC00NDJhLTk1NmEtNjEzZTkxYjM4NzJkIiwiaXNzIjoibWRfcGF0IiwicmVhZE9ubHkiOnRydWUsInRva2VuVHlwZSI6InJlYWRfc2NhbGluZyIsImlhdCI6MTc1OTMyOTgzOX0.QNrYEA4yBEIcyEi5NbcLpQrCnKs46MhSSrTkQZIIKWA"
con = _connect_md(motherduck_token=READ_TOKEN)
# ПРИМЕР ЗАПРОСА
sql = '''select year("Отчетный период") as "Год", "Направление", "Код товара (4 знака)",
          sum("Значение (стоимость)") + sum(coalesce("Значение (стоимость) - ДЭИ", 0)) as "Денежная стоимость" from trade_data
                group by year("Отчетный период"), "Направление", "Код товара (4 знака)"
                having "Код товара (4 знака)" = '8705' order by "Год"'''
df: pd.DataFrame = con.execute(sql).fetch_df()
con.close()
df

     Год Направление Код товара (4 знака)  Денежная стоимость
0   2019     Экспорт                 8705        6.136057e+07
1   2019      Импорт                 8705        1.791208e+08
2   2020      Импорт                 8705        2.292569e+08
3   2020     Экспорт                 8705        1.052651e+07
4   2021     Экспорт                 8705        3.245105e+07
5   2021      Импорт                 8705        3.057731e+08
6   2022      Импорт                 8705        4.546718e+08
7   2022     Экспорт                 8705        3.610146e+07
8   2023     Экспорт                 8705        2.734883e+07
9   2023      Импорт                 8705        6.465087e+08
10  2024      Импорт                 8705        6.736837e+08
11  2024     Экспорт                 8705        3.336671e+07
12  2025      Импорт                 8705        2.801049e+08
13  2025     Экспорт                 8705        1.321277e+07

In [9]:
READ_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5kcmVldjEzQGdtYWlsLmNvbSIsInNlc3Npb24iOiJpdmFuZHJlZXYxMy5nbWFpbC5jb20iLCJwYXQiOiJtS3FreDdXeFZGdkFaNWVXbWFKR1pfQ2xocUg4TVNlVHM5Vi1raDJKRXpvIiwidXNlcklkIjoiNDA4NmNhZjItOTRiMC00NDJhLTk1NmEtNjEzZTkxYjM4NzJkIiwiaXNzIjoibWRfcGF0IiwicmVhZE9ubHkiOnRydWUsInRva2VuVHlwZSI6InJlYWRfc2NhbGluZyIsImlhdCI6MTc1OTMyOTgzOX0.QNrYEA4yBEIcyEi5NbcLpQrCnKs46MhSSrTkQZIIKWA"
con = _connect_md(motherduck_token=READ_TOKEN)
# ПРИМЕР ЗАПРОСА
sql = '''select * from trade_data where "Код товара (4 знака)" in ('9018', '9019', '9020', '9021', '9022', '9025', '9027', '9030', '9031')'''
df: pd.DataFrame = con.execute(sql).fetch_df()
con.close()
df

Error: Request failed: Your request timed out, the MotherDuck servers took too long to respond. Please try again later or contact support@motherduck.com for help. (DEADLINE_EXCEEDED, RPC 'SETUP_PLAN_FRAGMENTS', request id: '819d6454-44a6-459c-a727-a6b87ee0a0ac')

ЗАПИСЬ СРЕЗА В EXCEL

In [ ]:
output_file_name = "8705.xlsx"
df.to_excel(output_file_name, index=False)

## Бразилия

Один из самых простых и быстрых парсеров. Совершаем всего лишь один GET запрос по API и получаем детализированную статистику с разбивкой по ТН ВЭД с 6-ю разрядами (разрядность выше не доступна) за требуемый период помесячно. Обрабатываем и оформляем в pd.DataFrame полученный JSON.

In [10]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Brazil", params={"years": ["2025"]})
data = parser.parse()
data

Код состояния HTTP: 403

Exception: Ошибка клиента или сервера.

In [22]:
df = pd.read_csv("../MD_base.csv")
df

/var/folders/8d/cnlnd7c93fj81tn1mzz4c1nm0000gn/T/ipykernel_14435/2836897298.py:1: DtypeWarning: Columns (4,5,6,13,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../MD_base.csv")

,Отчетный период,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ,Единица стоимости
0,2025-08-01,CША,Экспорт,1.0,106,10619,1061991.0,106199195.0,23520.000000,USD,382.0,NO,0.0,NaN,NaN,NaN
1,2025-08-01,CША,Экспорт,8.0,813,81340,8134020.0,813402060.0,3250.000000,USD,512.0,KG,0.0,NaN,NaN,NaN
2,2025-08-01,CША,Экспорт,9.0,901,90121,9012100.0,901210049.0,4261.000000,USD,412.0,KG,0.0,NaN,NaN,NaN
3,2025-08-01,CША,Экспорт,9.0,902,90210,9021010.0,902101050.0,8199.000000,USD,323.0,KG,0.0,NaN,NaN,NaN
4,2025-08-01,CША,Экспорт,9.0,902,90230,9023000.0,902300090.0,9679.000000,USD,358.0,KG,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4603442,2019-01-01,Ukraine,Импорт,96.0,9608,960860,NaN,NaN,700.951650,USD,30.0,килограмм,NaN,NaN,NaN,NaN
4603443,2019-01-01,Ukraine,Импорт,96.0,9609,960910,NaN,NaN,6268.608326,USD,694.0,килограмм,NaN,NaN,NaN,NaN
4603444,2019-01-01,Ukraine,Импорт,96.0,9613,961380,NaN,NaN,38.814912,USD,1.0,килограмм,NaN,NaN,NaN,NaN
4603445,2019-01-01,Ukraine,Импорт,96.0,9617,961700,NaN,NaN,1070.834932,USD,72.0,килограмм,NaN,NaN,NaN,NaN
4603446,2019-01-01,Ukraine,Импорт,96.0,9618,961800,NaN,NaN,4036.750872,USD,513.0,килограмм,NaN,NaN,NaN,NaN

In [32]:
import numpy as np

df = pd.read_csv("../MD_base.csv")
df['Отчетный период'] = pd.to_datetime(df['Отчетный период'])
df['Код товара (4 знака)'] = df['Код товара (4 знака)'].astype(str).str.replace('.0', '').str.zfill(4)
df['Код товара (2 знака)'] = df['Код товара (2 знака)'].astype(str).str.replace('.0', '').str.zfill(2)
df['Значение (стоимость)'] = df['Значение (стоимость)'].replace({np.nan: 0, 'nan': 0}).astype(float)
df['Значение (масса)'] = df['Значение (масса)'].replace({np.nan: 0, 'nan': 0}).astype(float)
df['Дополнительная единица измерения (ДЭИ)'] = df['Дополнительная единица измерения (ДЭИ)'].replace({np.nan: 0, 'nan': 0}).astype(float)
df['Значение (стоимость) - ДЭИ'] = df['Значение (стоимость) - ДЭИ'].replace({np.nan: 0, 'nan': 0}).astype(float)
df.groupby('Страна-партнер', as_index=False)['Отчетный период'].max().sort_values(by='Отчетный период').head(50)

/var/folders/8d/cnlnd7c93fj81tn1mzz4c1nm0000gn/T/ipykernel_14435/3935062269.py:3: DtypeWarning: Columns (4,5,6,13,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../MD_base.csv")

                                       Страна-партнер Отчетный период
41                                     United Kingdom      2019-12-01
55                                        Таджикистан      2025-06-01
53                                            Мексика      2025-06-01
59                                            Эквадор      2025-06-01
43                                        Азербайджан      2025-06-01
45                                           Беларусь      2025-06-01
8                                                 CША      2025-08-01
25                               Moldova, Republic of      2025-08-01
13                                            Georgia      2025-08-01
40                                            Ukraine      2025-08-01
36        Spain (incl. Canary Islands 'XB' from 1997)      2025-09-01
0                                             Albania      2025-09-01
34                                           Slovakia      2025-09-01
33                                             Serbia      2025-09-01
32                                            Romania      2025-09-01
31                                           Portugal      2025-09-01
35                                           Slovenia      2025-09-01
37                                             Sweden      2025-09-01
42                  United Kingdom (Northern Ireland)      2025-09-01
39                                            Türkiye      2025-09-01
44                                            Армения      2025-09-01
47                                            Вьетнам      2025-09-01
48                                            Гонконг      2025-09-01
49                                              Индия      2025-09-01
50                                          Казахстан      2025-09-01
51                                           Киргизия      2025-09-01
58                                         Узбекистан      2025-09-01
38     Switzerland (incl. Liechtenstein 'LI' -> 1994)      2025-09-01
29  Norway (incl. Svalbard and Jan Mayen 'SJ' -> 1...      2025-09-01
30                                             Poland      2025-09-01
27                                        Netherlands      2025-09-01
1                                             Austria      2025-09-01
2             Belgium (incl. Luxembourg 'LU' -> 1998)      2025-09-01
3                              Bosnia and Herzegovina      2025-09-01
4                                            Bulgaria      2025-09-01
5                                             Croatia      2025-09-01
6                                              Cyprus      2025-09-01
7                                             Czechia      2025-09-01
9                                             Denmark      2025-09-01
28                                    North Macedonia      2025-09-01
11                                            Finland      2025-09-01
12  France (incl. Saint Barthélemy 'BL' -> 2012; i...      2025-09-01
10                                            Estonia      2025-09-01
15                                             Greece      2025-09-01
26                                         Montenegro      2025-09-01
24                                              Malta      2025-09-01
23                                         Luxembourg      2025-09-01
14  Germany (incl. German Democratic Republic 'DD'...      2025-09-01
21                                             Latvia      2025-09-01
22                                          Lithuania      2025-09-01

In [34]:
df[df['Код товара (4 знака)'].isin(['9018', '9019', '9020', '9021', '9022', '9025', '9027', '9030', '9031'])]

,Отчетный период,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ,Единица стоимости
139,2025-08-01,CША,Экспорт,90,9018,901819,90181995.0,9.018200e+09,29500.000000,USD,4.0,NO,0.0,NaN,0.0,NaN
140,2025-08-01,CША,Экспорт,90,9018,901819,90181995.0,9.018200e+09,52000.000000,USD,644.0,NO,0.0,NaN,0.0,NaN
141,2025-08-01,CША,Экспорт,90,9018,901849,90184940.0,9.018494e+09,30244.000000,USD,189.0,GRS,0.0,NaN,0.0,NaN
142,2025-08-01,CША,Экспорт,90,9018,901849,90184980.0,9.018498e+09,15161.000000,USD,3700.0,NO,0.0,NaN,0.0,NaN
143,2025-08-01,CША,Экспорт,90,9018,901890,90189080.0,9.018908e+09,35947.000000,USD,335.0,NO,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4601858,2019-01-01,Ukraine,Импорт,90,9030,903090,NaN,NaN,131914.762453,USD,570.0,килограмм,0.0,NaN,0.0,NaN
4601859,2019-01-01,Ukraine,Импорт,90,9031,903110,NaN,NaN,17335.424772,USD,4811.0,килограмм,0.0,NaN,0.0,NaN
4601860,2019-01-01,Ukraine,Импорт,90,9031,903120,NaN,NaN,28606.590315,USD,1807.0,килограмм,0.0,NaN,0.0,NaN
4601861,2019-01-01,Ukraine,Импорт,90,9031,903180,NaN,NaN,208326.483643,USD,10547.0,килограмм,0.0,NaN,0.0,NaN
4601862,2019-01-01,Ukraine,Импорт,90,9031,903190,NaN,NaN,1647.350540,USD,44.0,килограмм,0.0,NaN,0.0,NaN

In [41]:
df.isna().sum()

Отчетный период                                 0
Страна-партнер                                  0
Направление                                     0
Код товара (2 знака)                            0
Код товара (4 знака)                            0
Код товара (6 знаков)                      188618
Код товара (8 знаков)                     3805903
Код товара (10 знаков)                    4369754
Значение (стоимость)                            0
Единицы стоимости                            2401
Значение (масса)                                0
Единица объема                              20700
Дополнительная единица измерения (ДЭИ)          0
ДЭИ, описание                             3773747
Значение (стоимость) - ДЭИ                      0
Единица стоимости                         4601046
dtype: int64

In [35]:
df.columns

Index(['Отчетный период', 'Страна-партнер', 'Направление',
       'Код товара (2 знака)', 'Код товара (4 знака)', 'Код товара (6 знаков)',
       'Код товара (8 знаков)', 'Код товара (10 знаков)',
       'Значение (стоимость)', 'Единицы стоимости', 'Значение (масса)',
       'Единица объема', 'Дополнительная единица измерения (ДЭИ)',
       'ДЭИ, описание', 'Значение (стоимость) - ДЭИ', 'Единица стоимости'],
      dtype='object')

In [42]:
full = prepare(df)
full = full.groupby(
    ['Отчетный период', 'Страна-партнер', 'Направление',
     'Код товара (2 знака)', 'Код товара (4 знака)', 'Единицы стоимости',
     'Единица объема', 'ДЭИ, описание', 'europe_non_eu', 'asia',
     'america', 'middle_east', 'eu_27', 'nato', 'unfriendly', 'friendly',
     'brics', 'sco', 'cis', 'eaeu', 'africa', 'oceania'],
    as_index=False,
    dropna=False
)[['Значение (стоимость)',
   'Значение (стоимость) - ДЭИ',
   'Значение (масса)',
   'Дополнительная единица измерения (ДЭИ)']].sum()
full = full[full['Код товара (4 знака)'].isin(['9018', '9019', '9020', '9021', '9022', '9025', '9027', '9030', '9031'])]
full = full[full['Направление'] == 'Экспорт']
full

,Отчетный период,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Единицы стоимости,Единица объема,"ДЭИ, описание",europe_non_eu,asia,...,brics,sco,cis,eaeu,africa,oceania,Значение (стоимость),Значение (стоимость) - ДЭИ,Значение (масса),Дополнительная единица измерения (ДЭИ)
741,2019-01-01,Austria,Экспорт,90,9018,NaN,килограмм,NaN,0,0,...,0,0,0,0,0,0,3.419788e+05,0.0,3315.0,0.0
742,2019-01-01,Austria,Экспорт,90,9021,NaN,килограмм,NaN,0,0,...,0,0,0,0,0,0,2.525504e+05,0.0,655.0,0.0
743,2019-01-01,Austria,Экспорт,90,9022,NaN,килограмм,NaN,0,0,...,0,0,0,0,0,0,2.842393e+04,0.0,14.0,0.0
746,2019-01-01,Austria,Экспорт,90,9025,NaN,килограмм,NaN,0,0,...,0,0,0,0,0,0,3.857517e+03,0.0,23.0,0.0
748,2019-01-01,Austria,Экспорт,90,9027,NaN,килограмм,NaN,0,0,...,0,0,0,0,0,0,1.023569e+06,0.0,7951.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2150529,2025-10-01,Таиланд,Экспорт,90,9025,NaN,NO,NaN,0,0,...,0,0,0,0,0,0,1.116918e+04,0.0,12.0,0.0
2150533,2025-10-01,Таиланд,Экспорт,90,9030,NaN,NO,NaN,0,0,...,0,0,0,0,0,0,2.190002e+04,0.0,2.0,0.0
2150534,2025-10-01,Таиланд,Экспорт,90,9031,NaN,KG,NaN,0,0,...,0,0,0,0,0,0,7.154030e+03,0.0,2.0,0.0
2150535,2025-10-01,Таиланд,Экспорт,90,9031,NaN,NO,NaN,0,0,...,0,0,0,0,0,0,4.080560e+02,0.0,14.0,0.0
2150536,2025-10-01,Таиланд,Экспорт,90,9031,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,7.192171e+04,0.0,0.0,0.0

In [45]:
import requests

res = requests.post(url="https://comtradeplus.un.org/api/Trade/getDataComtrade?selectedProductOptionsModified=C&selectedFrequencyOptionsModified=M&selectedClassificationOptionsModified=HS&selectValuePeriodsModified=202501,202502,202503,202504,202505,202506,202507,202508,202509,202510,202511,202512&selectValueReportersModified=all&selectValuePartnersModified=643&selectValueTradeflowsModified=x&selectValueCommodityCodesModified=9018,9019,9020,9021,9022,9025,9027,9030,9031&selectValueCustomsCodesModified=c00&selectValueTransportCodesModified=0&selectValueSecondPartnersModified=0&selectValueAggregateByModified=none&selectValueBreakdownModeModified=plus&selectValueincludeDescModified=True&selectValuecountOnlyModified=False")
res.text

''

In [ ]:
prepare(data)

## Корея

Долгий парсер. Полный сбор базы по Корее ~ 3-4 часа. Один год ~ 30 минут. Сайт обновляется динамически, публичные/скрытые API запросы не предусмотрены. Эмулируем реального пользователя браузера с помощью библиотеки Selenium. C 2019 года по 2025 последовательно отправяем HS4 по 100 штук, они разбиваются автоматически на HS6, собираем динамически сформированную таблицу, переходя по страницам.

Ограничения:
1. Один запрос может включать не более ста HS4 кодов;
2. Один запрос не может быть по разным годам.

In [2]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Korea", params={"years": ["2025"]})
data = parser.parse()
data

Собрано HS4 (батчей по 100 шт): 100%|██████████| 12/12 [29:10<00:00, 145.90s/batch]
Парсим 2025 год: 100%|██████████| 1/1 [29:10<00:00, 1750.79s/it]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-10-01,Республика Корея,Россия,Экспорт,03,0303,030332,NaN,NaN,25000.0,USD,27.3,тонн,NaN,NaN,NaN
1,2025-10-01,Республика Корея,Россия,Экспорт,03,0303,030339,NaN,NaN,3074000.0,USD,1063.9,тонн,NaN,NaN,NaN
2,2025-10-01,Республика Корея,Россия,Экспорт,03,0303,030351,NaN,NaN,3171000.0,USD,3554.7,тонн,NaN,NaN,NaN
3,2025-10-01,Республика Корея,Россия,Экспорт,03,0303,030353,NaN,NaN,1249000.0,USD,2257.0,тонн,NaN,NaN,NaN
4,2025-10-01,Республика Корея,Россия,Экспорт,03,0303,030363,NaN,NaN,445000.0,USD,163.5,тонн,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10300,2025-01-01,Республика Корея,Россия,Импорт,90,9022,902290,NaN,NaN,105000.0,USD,0.2,тонн,NaN,NaN,NaN
10301,2025-01-01,Республика Корея,Россия,Импорт,90,9026,902610,NaN,NaN,4000.0,USD,0.1,тонн,NaN,NaN,NaN
10302,2025-01-01,Республика Корея,Россия,Импорт,90,9031,903180,NaN,NaN,11000.0,USD,0.2,тонн,NaN,NaN,NaN
10303,2025-01-01,Республика Корея,Россия,Импорт,90,9032,903289,NaN,NaN,21000.0,USD,0.5,тонн,NaN,NaN,NaN
10304,2025-01-01,Республика Корея,Россия,Импорт,95,9503,950300,NaN,NaN,449000.0,USD,18.6,тонн,NaN,NaN,NaN

## Турция

<span style="color: red;">С недавнего времени сервер Турции не доступен.</span>

Европейский парсер включает в себя турецкую статистику. Для ее извлечения запустите парсер по Европе и в итоговой таблице оставьте только Турцию в качестве исходной страны.

In [3]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Turkey", params={"years": ["2019", "2020"]})
data = parser.parse()
data

The chromedriver version (138.0.7204.92) detected in PATH at /usr/local/bin/chromedriver might not be compatible with the detected chrome version (139.0.7258.157); currently, chromedriver 139.0.7258.154 is recommended for chrome 139.*, so it is advised to delete the driver in PATH and retry
Собрано HS6 (батчей по 25 шт):   2%|▏         | 5/224 [00:13<09:12,  2.52s/batch]

[retry] batch 125-149: no response within 60 s

Собрано HS6 (батчей по 25 шт):  35%|███▍      | 78/224 [04:41<06:41,  2.75s/batch]

[retry] batch 1950-1974: no response within 60 s

Собрано HS6 (батчей по 25 шт):  38%|███▊      | 84/224 [06:10<10:17,  4.41s/batch]

KeyboardInterrupt:

## Япония

Достаточно и быстрый и простой парсер. Отправляем GET запросы по API.
Ограничения:
1. Статистика доступна с 2021-ого года;
2. Один запрос может включать не более ста HS8 кодов;
3. Отдельные базы для экспорта и импорта;
4. Необходимость регистрации для использования API - авторизация не требуется, достаточно один раз зарегистрироваться и пройти верификацию, получить apiID и использовать его в запросах.

Единица измерения стоимости - йены. Переводим в доллары, используя средний курс JPY/USD за месяц. Для этого обращаемся по API к stats.bis.org

In [4]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Japan", params={"years": ['2019', '2020', '2021', '2022', '2023', '2024', "2025"]})
data = parser.parse()
data

Спаршено HS8 (батчей по 100 шт) - export:   0%|          | 0/2 [01:27<?, ?batch/s]

KeyboardInterrupt:

## Казахстан

Казахстан публикует статистику о своей ВЭД с ЕАЭС помесячно по товарам (HS6) в виде RAR архивов на сайте. Получаем ссылки на архивы, скачиваем в директорию data, распаковываем и для каждого месяца собираем таблицы № 9, забирая строки, относящиеся к России. Приводим к единому формату. Ограничения: статистика доступна с 2021-ого года.

In [12]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Kazakhstan", params={"years": ["2025"]})
data = parser.parse()
data

Парсим 2025 год:  17%|█▋        | 1/6 [00:01<00:06,  1.22s/it]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-01-01,Казахстан,Россия,Импорт,10,1012,101210,NaN,NaN,2193.00,USD,2.30000,тонн,6.0,Штука,NaN
1,2025-01-01,Казахстан,Россия,Импорт,10,1012,101290,NaN,NaN,8859.07,USD,8.79000,тонн,43.0,Штука,NaN
2,2025-01-01,Казахстан,Россия,Импорт,10,1019,101900,NaN,NaN,15173.00,USD,9.37000,тонн,52.0,Штука,NaN
3,2025-01-01,Казахстан,Россия,Импорт,10,1022,102290,NaN,NaN,3065.00,USD,15.00000,тонн,45.0,Штука,NaN
4,2025-01-01,Казахстан,Россия,Импорт,10,1031,103100,NaN,NaN,105688.33,USD,31.90000,тонн,248.0,Штука,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4633,2025-01-01,Казахстан,Россия,Экспорт,96,9616,9616200,NaN,NaN,69.80,USD,0.01938,тонн,NaN,NaN,NaN
4634,2025-01-01,Казахстан,Россия,Экспорт,96,9617,9617000,NaN,NaN,42891.77,USD,2.34822,тонн,NaN,NaN,NaN
4635,2025-01-01,Казахстан,Россия,Экспорт,96,9619,9619000,NaN,NaN,164572.26,USD,0.92600,тонн,NaN,NaN,NaN
4636,2025-01-01,Казахстан,Россия,Экспорт,96,9620,9620000,NaN,NaN,1256.23,USD,0.27500,тонн,NaN,NaN,NaN
4637,2025-01-01,Казахстан,Россия,Экспорт,99,9999,9999990,NaN,NaN,52856.00,USD,2.69300,тонн,NaN,NaN,NaN

## Гонконг

Достаточно долгий парсер - время работы ~ 20 минут. Отправяем GET запросы по API и получаем JSON с детализацией по HS6. 
Ограничения:
1. Один запрос может включать не более двадцати HS6 кодов;
2. Отдельные базы для экспорта и импорта;

Единица измерения стоимости - гонгконгский доллар. Переводим в доллары США, используя средний курс HKD/USD за месяц. Для этого обращаемся по API к stats.bis.org

In [5]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Hong Kong", params={"years": ["2019", "2020", "2021", "2022", "2023", "2024", "2025"], "final_month": "12"})
data = parser.parse()
data

Собрано HS6 (батчей по 20), imports: 100%|██████████| 281/281 [10:15<00:00,  2.19s/batch]
Собрано HS6 (батчей по 20), exports: 100%|██████████| 281/281 [12:37<00:00,  2.69s/batch]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.
https://stats.bis.org/api/v1/data/BIS,WS_XRU,1.0/M.HK.HKD.A/all?startPeriod=2019-01&endPeriod=2026-04

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-12-01,Гонконг,Россия,Импорт,02,0202,020230,NaN,NaN,7.915964e+04,USD,4425.0,KILOGRAM,NaN,NaN,NaN
1,2025-12-01,Гонконг,Россия,Импорт,02,0203,020322,NaN,NaN,1.066599e+05,USD,30814.0,KILOGRAM,NaN,NaN,NaN
2,2025-12-01,Гонконг,Россия,Импорт,02,0203,020329,NaN,NaN,3.691718e+06,USD,1062094.0,KILOGRAM,NaN,NaN,NaN
3,2025-12-01,Гонконг,Россия,Импорт,02,0207,020727,NaN,NaN,1.055034e+05,USD,27000.0,KILOGRAM,NaN,NaN,NaN
4,2025-12-01,Гонконг,Россия,Импорт,03,0304,030489,NaN,NaN,1.002346e+04,USD,792.0,KILOGRAM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37214,2019-01-01,Гонконг,Россия,Экспорт,96,9606,960610,NaN,NaN,2.550369e+03,USD,28.0,KILOGRAM,NaN,NaN,NaN
37215,2019-01-01,Гонконг,Россия,Экспорт,96,9606,960621,NaN,NaN,3.315480e+04,USD,371.0,KILOGRAM,NaN,NaN,NaN
37216,2019-01-01,Гонконг,Россия,Экспорт,96,9606,960630,NaN,NaN,1.275185e+02,USD,12.0,KILOGRAM,NaN,NaN,NaN
37217,2019-01-01,Гонконг,Россия,Экспорт,96,9608,960810,NaN,NaN,2.550369e+02,USD,110.0,UNIT,NaN,NaN,NaN
37218,2019-01-01,Гонконг,Россия,Экспорт,96,9620,962000,NaN,NaN,2.749298e+05,USD,16580.0,KILOGRAM,NaN,NaN,NaN

In [7]:
hk_med = prepare(data)
hk_med = hk_med.groupby(['Отчетный период', 'Страна-партнер', 'Направление',
       'Код товара (2 знака)', 'Код товара (4 знака)', 'Единицы стоимости',
       'Единица объема', 'europe_non_eu', 'asia',
       'america', 'middle_east', 'eu_27', 'nato', 'unfriendly', 'friendly',
       'brics', 'sco', 'cis', 'eaeu', 'africa', 'oceania'], as_index=False)[['Значение (стоимость)', 'Значение (масса)']].sum()
hk_med = hk_med[hk_med['Код товара (4 знака)'].isin(['9018', '9019', '9020', '9021', '9022', '9025', '9027', '9030', '9031'])]
hk_med = hk_med[hk_med['Направление'] == 'Импорт']
hk_med

,Отчетный период,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Единицы стоимости,Единица объема,europe_non_eu,asia,america,...,unfriendly,friendly,brics,sco,cis,eaeu,africa,oceania,Значение (стоимость),Значение (масса)
180,2019-01-01,Гонконг,Импорт,90,9018,USD,UNIT,0,0,0,...,0,1,0,0,0,0,0,0,1.927569e+06,244.0
181,2019-01-01,Гонконг,Импорт,90,9021,USD,KILOGRAM,0,0,0,...,0,1,0,0,0,0,0,0,9.308847e+04,216.0
183,2019-01-01,Гонконг,Импорт,90,9025,USD,UNIT,0,0,0,...,0,1,0,0,0,0,0,0,2.736546e+05,121556.0
186,2019-01-01,Гонконг,Импорт,90,9027,USD,KILOGRAM,0,0,0,...,0,1,0,0,0,0,0,0,4.195357e+04,775.0
188,2019-01-01,Гонконг,Импорт,90,9030,USD,KILOGRAM,0,0,0,...,0,1,0,0,0,0,0,0,6.375923e+02,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21032,2025-12-01,Гонконг,Импорт,90,9027,USD,UNIT,0,0,0,...,0,1,0,0,0,0,0,0,5.560451e+05,479.0
21035,2025-12-01,Гонконг,Импорт,90,9030,USD,KILOGRAM,0,0,0,...,0,1,0,0,0,0,0,0,5.679961e+04,44.0
21036,2025-12-01,Гонконг,Импорт,90,9030,USD,UNIT,0,0,0,...,0,1,0,0,0,0,0,0,6.060339e+05,541.0
21037,2025-12-01,Гонконг,Импорт,90,9031,USD,KILOGRAM,0,0,0,...,0,1,0,0,0,0,0,0,1.947122e+06,1565.0
21038,2025-12-01,Гонконг,Импорт,90,9031,USD,UNIT,0,0,0,...,0,1,0,0,0,0,0,0,1.455844e+06,7250.0

In [8]:
hk_med.to_csv('hk_pre_final.csv', index=False)

## Тайвань

Время работы парсера ~ 15 минут. Сайт обновляется динамически, публичные/скрытые API запросы не предусмотрены. Эмулируем реального пользователя браузера с помощью библиотеки Selenium. Отправяем HS6 по 100 штук (ограничений нет, но сайт зависает), и собираем динамически сформированную таблицу.
Ограничения:
1. Каптча;

Каптча представляет собой последовательность цифр на разноцветном, резком фоне. Обходим ее с помощью локальной CV модели microsoft/trocr-base-printed среднего размера. Делаем скриншот каптчи, кладем в директорию data, загружаем в модель и получаем ответ. Простое решение без дообучения. Модель проходит каптчу в 80% случаев. Иначе - потворяем процедуру. При наличии времени и желании можно собрать датасет из этих каптч, разметить и обучить YOLO.

In [9]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Taiwan", params={"version_main": 146, "years": ['2019', '2020', '2021', '2022', '2023', '2024', "2025"]})
data = parser.parse()
data

Some weights of VisionEncoderDecoderModel were not initialized from the model checkpoint at microsoft/trocr-base-printed and are newly initialized: ['encoder.pooler.dense.bias', 'encoder.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
Device set to use cpu
Собрано HS6 (батчей по 100 штук): 100%|██████████| 56/56 [2:19:48<00:00, 149.80s/batch]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-12-01,Тайвань,Россия,Импорт,03,0303,030383,NaN,NaN,166000.0,USD,7020.0,килограмм,NaN,NaN,NaN
1,2025-12-01,Тайвань,Россия,Импорт,03,0303,030389,NaN,NaN,66000.0,USD,2718.0,килограмм,NaN,NaN,NaN
2,2025-12-01,Тайвань,Россия,Импорт,03,0306,030614,NaN,NaN,4554000.0,USD,225076.0,килограмм,NaN,NaN,NaN
3,2025-12-01,Тайвань,Россия,Импорт,03,0306,030617,NaN,NaN,6000.0,USD,305.0,килограмм,NaN,NaN,NaN
4,2025-12-01,Тайвань,Россия,Импорт,03,0306,030633,NaN,NaN,231000.0,USD,4837.0,килограмм,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46235,2019-01-01,Тайвань,Россия,Экспорт,96,9607,960720,NaN,NaN,21000.0,USD,907.0,килограмм,NaN,NaN,NaN
46236,2019-01-01,Тайвань,Россия,Экспорт,96,9615,961519,NaN,NaN,48000.0,USD,3958.0,килограмм,NaN,NaN,NaN
46237,2019-01-01,Тайвань,Россия,Экспорт,96,9615,961590,NaN,NaN,2000.0,USD,53.0,килограмм,NaN,NaN,NaN
46238,2019-01-01,Тайвань,Россия,Экспорт,96,9616,961610,NaN,NaN,2000.0,USD,173.0,килограмм,NaN,NaN,NaN
46239,2019-01-01,Тайвань,Россия,Экспорт,96,9619,961900,NaN,NaN,154000.0,USD,28274.0,килограмм,NaN,NaN,NaN

In [10]:
tw_med = prepare(data)
tw_med = tw_med.groupby(['Отчетный период', 'Страна-партнер', 'Направление',
       'Код товара (2 знака)', 'Код товара (4 знака)', 'Единицы стоимости',
       'Единица объема', 'europe_non_eu', 'asia',
       'america', 'middle_east', 'eu_27', 'nato', 'unfriendly', 'friendly',
       'brics', 'sco', 'cis', 'eaeu', 'africa', 'oceania'], as_index=False)[['Значение (стоимость)', 'Значение (масса)']].sum()
tw_med = tw_med[tw_med['Код товара (4 знака)'].isin(['9018', '9019', '9020', '9021', '9022', '9025', '9027', '9030', '9031'])]
tw_med = tw_med[tw_med['Направление'] == 'Импорт']
tw_med

,Отчетный период,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Единицы стоимости,Единица объема,europe_non_eu,asia,america,...,unfriendly,friendly,brics,sco,cis,eaeu,africa,oceania,Значение (стоимость),Значение (масса)
237,2019-01-01,Тайвань,Импорт,90,9018,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,98000.0,937.0
238,2019-01-01,Тайвань,Импорт,90,9019,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,65000.0,1288.0
239,2019-01-01,Тайвань,Импорт,90,9020,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,88000.0,4766.0
240,2019-01-01,Тайвань,Импорт,90,9021,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,44000.0,163.0
242,2019-01-01,Тайвань,Импорт,90,9025,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,27000.0,753.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24060,2025-11-01,Тайвань,Импорт,90,9027,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,85000.0,215.0
24063,2025-11-01,Тайвань,Импорт,90,9030,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,2000.0,19.0
24243,2025-12-01,Тайвань,Импорт,90,9018,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,646000.0,13512.0
24244,2025-12-01,Тайвань,Импорт,90,9019,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,61000.0,1743.0
24246,2025-12-01,Тайвань,Импорт,90,9027,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,405000.0,16289.0

In [12]:
tw_med.to_csv('tw_final.csv', index=False)

## Тайланд

Долгий парсер. Один год собирается приблизительно за час. Отправляем POST запросы по скрытому API, итерируясь по HS2 кодам (разбиваются на HS6), месяцам, годам и направлению (экспорт/импорт). Оформляем и приводим к единому виду полученные JSON файлы. 
Ограничения:
1. Один запрос может включать не более одного HS2 кода;
2. Один запрос может включать не более одного месяца;
3. Один запрос может включать не более одного года;
3. Отдельные базы для экспорта и импорта;

In [1]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Thailand", params={"years": ["2025"]})
data2 = parser.parse()
data2

/Users/ivanandreev/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Собрано HS2, exports, 01.2025: 100%|██████████| 99/99 [02:08<00:00,  1.29s/it]
Собрано HS2, exports, 02.2025: 100%|██████████| 99/99 [02:17<00:00,  1.39s/it]
Собрано HS2, exports, 03.2025: 100%|██████████| 99/99 [02:09<00:00,  1.30s/it]
Собрано HS2, exports, 04.2025: 100%|██████████| 99/99 [02:15<00:00,  1.36s/it]
Собрано HS2, exports, 05.2025: 100%|██████████| 99/99 [02:03<00:00,  1.25s/it]
Собрано HS2, exports, 06.2025: 100%|██████████| 99/99 [01:54<00:00,  1.15s/it]
Собрано HS2, exports, 07.2025: 100%|██████████| 99/99 [01:49<00:00,  1.10s/it]
Собрано HS2, exports, 08.2025: 100%|██████████| 99/99 [01:48<00:00,  1.10s/it]
Собрано HS2, exports, 09.2025: 100%|██████████| 99/99 [02:04<00:00,  1.26s/it]
Собрано HS2, exports, 10.2025: 100%|██████████| 99/99 [02:08<00:00,  1.30s/it]
Собрано HS2, exports, 11.2025: 100%|██████████| 99/99 [02:19<00:00,  1.41s/it]
Собрано HS2, exports, 12.2025: 100%|██████████| 99/99 [02:25<00:00,  1.47s/it]
Собрано HS2, imports, 01.2025: 100%|██████████| 99/99 [02:17<00:00,  1.39s/it]
Собрано HS2, imports, 02.2025: 100%|██████████| 99/99 [02:00<00:00,  1.22s/it]
Собрано HS2, imports, 03.2025: 100%|██████████| 99/99 [02:14<00:00,  1.35s/it]
Собрано HS2, imports, 04.2025: 100%|██████████| 99/99 [01:58<00:00,  1.19s/it]
Собрано HS2, imports, 05.2025: 100%|██████████| 99/99 [02:02<00:00,  1.24s/it]
Собрано HS2, imports, 06.2025: 100%|██████████| 99/99 [02:00<00:00,  1.21s/it]
Собрано HS2, imports, 07.2025: 100%|██████████| 99/99 [02:20<00:00,  1.42s/it]
Собрано HS2, imports, 08.2025: 100%|██████████| 99/99 [01:53<00:00,  1.15s/it]
Собрано HS2, imports, 09.2025: 100%|██████████| 99/99 [01:58<00:00,  1.19s/it]
Собрано HS2, imports, 10.2025: 100%|██████████| 99/99 [01:57<00:00,  1.18s/it]
Собрано HS2, imports, 11.2025: 100%|██████████| 99/99 [02:06<00:00,  1.28s/it]
Собрано HS2, imports, 12.2025: 100%|██████████| 99/99 [02:05<00:00,  1.27s/it]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-12-01,Таиланд,Россия,Импорт,01,0106,010619,NaN,NaN,3.726475e+02,USD,6.0,NO,NaN,NaN,NaN
1,2025-12-01,Таиланд,Россия,Импорт,03,0303,030353,NaN,NaN,1.813017e+06,USD,2420852.0,KG,NaN,NaN,NaN
2,2025-12-01,Таиланд,Россия,Импорт,03,0304,030494,NaN,NaN,1.421762e+06,USD,523700.0,KG,NaN,NaN,NaN
3,2025-12-01,Таиланд,Россия,Импорт,03,0307,030792,NaN,NaN,1.572676e+06,USD,77226.0,KG,NaN,NaN,NaN
4,2025-12-01,Таиланд,Россия,Импорт,03,0303,030312,NaN,NaN,1.123613e+06,USD,254880.0,KG,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9052,2025-01-01,Таиланд,Россия,Экспорт,96,9608,960820,NaN,NaN,2.419929e+02,USD,11.0,NO,NaN,NaN,NaN
9053,2025-01-01,Таиланд,Россия,Экспорт,96,9605,960500,NaN,NaN,1.421589e+02,USD,5.0,NO,NaN,NaN,NaN
9054,2025-01-01,Таиланд,Россия,Экспорт,96,9620,962000,NaN,NaN,2.500240e+01,USD,1.0,KG,NaN,NaN,NaN
9055,2025-01-01,Таиланд,Россия,Экспорт,96,9612,961210,NaN,NaN,1.799700e+01,USD,2.0,NO,NaN,NaN,NaN
9056,2025-01-01,Таиланд,Россия,Экспорт,96,9615,961590,NaN,NaN,9.672700e+00,USD,0.0,KG,NaN,NaN,NaN

In [ ]:
th_med = prepare(data2)
th_med = th_med.groupby(['Отчетный период', 'Страна-партнер', 'Направление',
       'Код товара (2 знака)', 'Код товара (4 знака)', 'Единицы стоимости',
       'Единица объема', 'europe_non_eu', 'asia',
       'america', 'middle_east', 'eu_27', 'nato', 'unfriendly', 'friendly',
       'brics', 'sco', 'cis', 'eaeu', 'africa', 'oceania'], as_index=False)[['Значение (стоимость)', 'Значение (масса)']].sum()
th_med = th_med[th_med['Код товара (4 знака)'].isin(['9018', '9019', '9020', '9021', '9022', '9025', '9027', '9030', '9031'])]
th_med = th_med[th_med['Направление'] == 'Импорт']
th_med

,Отчетный период,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Единицы стоимости,Единица объема,europe_non_eu,asia,america,...,unfriendly,friendly,brics,sco,cis,eaeu,africa,oceania,Значение (стоимость),Значение (масса)
264,2025-01-01,Таиланд,Импорт,90,9018,USD,KG,0,0,0,...,0,1,0,0,0,0,0,0,19111.1977,1686.0
265,2025-01-01,Таиланд,Импорт,90,9018,USD,other than tubular metal needles and needles f...,0,0,0,...,0,1,0,0,0,0,0,0,144310.2937,0.0
266,2025-01-01,Таиланд,Импорт,90,9019,USD,KG,0,0,0,...,0,1,0,0,0,0,0,0,2.6380,0.0
267,2025-01-01,Таиланд,Импорт,90,9020,USD,KG,0,0,0,...,0,1,0,0,0,0,0,0,51410.1013,214.0
268,2025-01-01,Таиланд,Импорт,90,9021,USD,KG,0,0,0,...,0,1,0,0,0,0,0,0,62067.0213,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4969,2025-12-01,Таиланд,Импорт,90,9020,USD,KG,0,0,0,...,0,1,0,0,0,0,0,0,31466.0859,13.0
4970,2025-12-01,Таиланд,Импорт,90,9021,USD,KG,0,0,0,...,0,1,0,0,0,0,0,0,189754.9479,340.0
4971,2025-12-01,Таиланд,Импорт,90,9025,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,61527.5897,52.0
4974,2025-12-01,Таиланд,Импорт,90,9027,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,2387.9888,1.0
4975,2025-12-01,Таиланд,Импорт,90,9031,USD,KG,0,0,0,...,0,1,0,0,0,0,0,0,44199.7379,3902.0

## США

Парсер таможни США работает исключительно через ВПН. Поэтому сначала мы парсим сайт free-proxy-list.net с бесплатными прокси серверами и ищем живой, рабочий прокси. Скорость парсинга зависит от качества найденного прокси. Отправляем GET запросы по API c первым HS рязрядом (разбивается на HS10). Получаем JSON файлы, оформляем и приводим к единому виду.
Ограничения:
1. Один запрос может включать не более одного HS1 разряда;
2. Отдельные базы для экспорта и импорта;
3. Не более 500 запросов в день (никак не отображается на работе).

In [2]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="USA", params={"years": ["2019", "2020", "2021", "2022", "2023", "2024", "2025"]})
data = parser.parse()
data

Собираю HS10 (первый разряд), exports:   0%|          | 0/10 [00:00<?, ?batch/s]

Ищем прокси.

Собираю HS10 (первый разряд), exports:  10%|█         | 1/10 [00:32<04:50, 32.31s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.

Собираю HS10 (первый разряд), exports:  20%|██        | 2/10 [01:05<04:21, 32.66s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.

Собираю HS10 (первый разряд), exports:  30%|███       | 3/10 [01:23<03:03, 26.21s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.
Прокси найден: 195.158.8.123:3128

Собираю HS10 (первый разряд), exports:  40%|████      | 4/10 [01:45<02:26, 24.49s/batch]

Ищем прокси.

Собираю HS10 (первый разряд), exports:  50%|█████     | 5/10 [01:58<01:42, 20.46s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.

Собираю HS10 (первый разряд), exports:  60%|██████    | 6/10 [02:11<01:11, 17.83s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.
Прокси найден: 195.158.8.123:3128

Собираю HS10 (первый разряд), exports:  70%|███████   | 7/10 [02:27<00:51, 17.15s/batch]

Ищем прокси.
Прокси найден: 195.158.8.123:3128

Собираю HS10 (первый разряд), exports:  80%|████████  | 8/10 [02:46<00:35, 17.65s/batch]

Ищем прокси.
Прокси найден: 195.158.8.123:3128

Собираю HS10 (первый разряд), exports:  90%|█████████ | 9/10 [04:03<00:36, 36.45s/batch]

Ищем прокси.
Прокси найден: 195.158.8.123:3128

Собираю HS10 (первый разряд), exports: 100%|██████████| 10/10 [04:27<00:00, 26.71s/batch]
Собираю HS10 (первый разряд), imports:   0%|          | 0/10 [00:00<?, ?batch/s]

Ищем прокси.

Собираю HS10 (первый разряд), imports:  10%|█         | 1/10 [00:22<03:19, 22.21s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.

Собираю HS10 (первый разряд), imports:  20%|██        | 2/10 [00:41<02:41, 20.22s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.
Прокси найден: 195.158.8.123:3128

Собираю HS10 (первый разряд), imports:  30%|███       | 3/10 [00:57<02:10, 18.57s/batch]

Ищем прокси.

Собираю HS10 (первый разряд), imports:  40%|████      | 4/10 [01:11<01:39, 16.52s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.
Прокси найден: 195.158.8.123:3128

Собираю HS10 (первый разряд), imports:  50%|█████     | 5/10 [01:23<01:16, 15.24s/batch]

Ищем прокси.

Собираю HS10 (первый разряд), imports:  60%|██████    | 6/10 [01:30<00:49, 12.28s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.

Собираю HS10 (первый разряд), imports:  70%|███████   | 7/10 [01:49<00:43, 14.63s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.

Собираю HS10 (первый разряд), imports:  80%|████████  | 8/10 [02:05<00:29, 14.88s/batch]

Прокси найден: 195.158.8.123:3128
Ищем прокси.
Прокси найден: 195.158.8.123:3128

Собираю HS10 (первый разряд), imports:  90%|█████████ | 9/10 [02:32<00:18, 18.63s/batch]

Ищем прокси.
Прокси найден: 195.158.8.123:3128

Собираю HS10 (первый разряд), imports: 100%|██████████| 10/10 [02:54<00:00, 17.43s/batch]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-12-01,CША,Россия,Импорт,01,0106,010619,01061991,0106199195,31590,USD,234,NO,0,-,NaN
1,2025-12-01,CША,Россия,Импорт,04,0406,040610,04061095,0406109500,6914,USD,2352,KG,0,-,NaN
2,2025-12-01,CША,Россия,Импорт,08,0802,080292,08029290,0802929000,1118700,USD,45000,KG,0,-,NaN
3,2025-12-01,CША,Россия,Импорт,09,0910,091099,09109960,0910996000,16167,USD,2542,KG,0,-,NaN
4,2025-12-01,CША,Россия,Импорт,10,1006,100630,10063090,1006309075,7335,USD,4938,KG,0,-,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115507,2019-01-01,CША,Россия,Экспорт,97,9703,970300,97030000,9703000000,233758,USD,0,NO,0,-,NaN
115508,2019-01-01,CША,Россия,Экспорт,97,9705,970500,97050000,9705000090,2756,USD,0,KG,0,-,NaN
115509,2019-01-01,CША,Россия,Экспорт,98,9801,980110,98011000,9801100000,446878,USD,0,X,0,-,NaN
115510,2019-01-01,CША,Россия,Экспорт,98,9802,980230,98023000,9802300000,208123,USD,0,X,0,-,NaN
115511,2019-01-01,CША,Россия,Экспорт,98,9880,988000,98800040,9880004000,1051591,USD,0,X,0,-,NaN

In [5]:
us_med = prepare(data)
us_med = us_med.groupby(['Отчетный период', 'Страна-партнер', 'Направление',
       'Код товара (2 знака)', 'Код товара (4 знака)', 'Единицы стоимости',
       'Единица объема', 'europe_non_eu', 'asia',
       'america', 'middle_east', 'eu_27', 'nato', 'unfriendly', 'friendly',
       'brics', 'sco', 'cis', 'eaeu', 'africa', 'oceania'], as_index=False)[['Значение (стоимость)', 'Значение (масса)']].sum()
us_med = us_med[us_med['Код товара (4 знака)'].isin(['9018', '9019', '9020', '9021', '9022', '9025', '9027', '9030', '9031'])]
us_med = us_med[us_med['Направление'] == 'Импорт']
us_med

,Отчетный период,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Единицы стоимости,Единица объема,europe_non_eu,asia,america,...,unfriendly,friendly,brics,sco,cis,eaeu,africa,oceania,Значение (стоимость),Значение (масса)
495,2019-01-01,CША,Импорт,90,9018,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,3398539,5699
496,2019-01-01,CША,Импорт,90,9019,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,188422,0
497,2019-01-01,CША,Импорт,90,9020,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,428331,1183
498,2019-01-01,CША,Импорт,90,9021,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,2361298,0
499,2019-01-01,CША,Импорт,90,9022,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,2418878,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50456,2025-12-01,CША,Импорт,90,9021,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,901695,17417
50457,2025-12-01,CША,Импорт,90,9022,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,1107698,950
50459,2025-12-01,CША,Импорт,90,9027,USD,KG,0,0,0,...,0,1,0,0,0,0,0,0,556727,4247
50460,2025-12-01,CША,Импорт,90,9027,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,1354195,386
50461,2025-12-01,CША,Импорт,90,9031,USD,NO,0,0,0,...,0,1,0,0,0,0,0,0,40155,4

In [6]:
us_med.to_csv('us_pre_final.csv', index=False)

## Мексика

Парсер таможни Мексики работает через ВПН. Поэтому сначала мы парсим сайт free-proxy-list.net с бесплатными прокси серверами и ищем живой, рабочий прокси. Скорость парсинга зависит от качества найденного прокси. Сайт обновляется динамически, публичные/скрытые API запросы не предусмотрены. Эмулируем реального пользователя браузера с помощью библиотеки Selenium. Скачиваем таблицы с весом и стоимостью, оформляем в нужном виде.
Ограничения:
1. Вес и стоимость операций разделены на разные БД
2. Необходимость proxy

In [4]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Mexico", params={"years": ["2025"]})
data = parser.parse()
data

Ищем прокси:   1%|          | 1/99 [01:03<1:43:38, 63.45s/it]

Прокси найден: 54.227.110.131:1001

Ищем прокси:   2%|▏         | 2/99 [06:16<5:39:30, 210.01s/it]

Прокси мертв. Продолжаем поиск.

Ищем прокси:   8%|▊         | 8/99 [09:55<1:02:44, 41.37s/it]

Прокси найден: 95.217.104.39:8888
Прокси мертв. Продолжаем поиск.

Ищем прокси:  16%|█▌        | 16/99 [14:34<19:30, 14.10s/it]

Прокси найден: 96.30.116.11:8293
Прокси мертв. Продолжаем поиск.

Ищем прокси:  22%|██▏       | 22/99 [19:00<35:35, 27.73s/it]

Прокси найден: 4.149.153.123:3128
Прокси мертв. Продолжаем поиск.

Ищем прокси:  38%|███▊      | 38/99 [23:44<19:20, 19.02s/it]

Прокси найден: 52.188.28.218:3128
Прокси мертв. Продолжаем поиск.

Ищем прокси: 100%|██████████| 99/99 [38:52<00:00, 23.56s/it]

KeyboardInterrupt:

## Европа

Европейский парсер способен собирать торговлю 44-ех европейских стран с россией с разбивкой по HS6. Обращаемся через GET запрос по API. По параметру countries можно запросить данные по конкретным странам, по умолчанию используется полный список.

Ограничения:
1. Стоимость выражается в евро
2. Ограничение на количество кодов HS6 на запрос
3. Экспорт и импорт находятся в отдельных БД

Единица измерения стоимости - евро. Переводим в доллары США, используя средний курс EUR/USD за месяц. Для этого обращаемся по API к stats.bis.org 

Полный список стран:
1. AL — Албания  
2. AT — Австрия  
3. BA — Босния и Герцеговина  
4. BE — Бельгия  
5. BG — Болгария  
6. CH — Швейцария  
7. CY — Кипр  
8. CZ — Чехия  
9. DE — Германия  
10. DK — Дания  
11. EE — Эстония  
12. ES — Испания  
13. FI — Финляндия  
14. FR — Франция  
15. GB — Великобритания  
16. GE — Грузия  
17. GR — Греция  
18. HR — Хорватия  
19. HU — Венгрия  
20. IE — Ирландия  
21. IS — Исландия  
22. IT — Италия  
23. LI — Лихтенштейн  
24. LT — Литва  
25. LU — Люксембург  
26. LV — Латвия  
27. MD — Молдова  
28. ME — Черногория  
29. MK — Северная Македония  
30. MT — Мальта  
31. NL — Нидерланды  
32. NO — Норвегия  
33. PL — Польша  
34. PT — Португалия  
35. RO — Румыния  
36. SE — Швеция  
37. SI — Словения  
38. SK — Словакия  
39. TR — Турция  
40. UA — Украина  
41. XI — Северная Ирландия
42. XK — Косово
43. XM
44. XS — Сербия (отдельно, исключая Косово)

In [2]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="EU", params={"years": ["2019", "2020", "2021", "2022", "2023", "2024", "2025"]})
data = parser.parse()
data

/Users/ivanandreev/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Собрано HS6 (батчей по 50 шт), flow=1: 100%|██████████| 155/155 [13:40<00:00,  5.29s/it]
Собрано HS6 (батчей по 50 шт), flow=2: 100%|██████████| 155/155 [12:37<00:00,  4.88s/it]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.

/Users/ivanandreev/Desktop/trade_project-main/scrapers/EU.py:94: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(EU.EU_params["CSV_PATH_EU"])

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-12-01,Estonia,Россия,Импорт,01,0101,010129,NaN,NaN,5672.750775,USD,2150.0,килограмм,NaN,NaN,NaN
1,2025-12-01,Latvia,Россия,Импорт,01,0106,010619,NaN,NaN,7807.203750,USD,3726.0,килограмм,NaN,NaN,NaN
2,2025-12-01,Poland,Россия,Импорт,01,0106,010619,NaN,NaN,1686.018806,USD,423.0,килограмм,NaN,NaN,NaN
3,2025-12-01,Poland,Россия,Импорт,01,0106,010631,NaN,NaN,665.040751,USD,2.0,килограмм,NaN,NaN,NaN
4,2025-12-01,"Moldova, Republic of",Россия,Импорт,02,0201,020130,NaN,NaN,22994.252315,USD,568.0,килограмм,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3013749,2019-01-01,Ukraine,Россия,Экспорт,96,9608,960860,NaN,NaN,700.951650,USD,30.0,килограмм,NaN,NaN,NaN
3013750,2019-01-01,Ukraine,Россия,Экспорт,96,9609,960910,NaN,NaN,6268.608326,USD,694.0,килограмм,NaN,NaN,NaN
3013751,2019-01-01,Ukraine,Россия,Экспорт,96,9613,961380,NaN,NaN,38.814912,USD,1.0,килограмм,NaN,NaN,NaN
3013752,2019-01-01,Ukraine,Россия,Экспорт,96,9617,961700,NaN,NaN,1070.834932,USD,72.0,килограмм,NaN,NaN,NaN
3013753,2019-01-01,Ukraine,Россия,Экспорт,96,9618,961800,NaN,NaN,4036.750872,USD,513.0,килограмм,NaN,NaN,NaN

In [14]:
eu_med = prepare(data)

In [15]:
eu_med.columns

Index(['Отчетный период', 'Страна-партнер', 'Направление',
       'Код товара (2 знака)', 'Код товара (4 знака)', 'Код товара (6 знаков)',
       'Код товара (8 знаков)', 'Код товара (10 знаков)',
       'Значение (стоимость)', 'Единицы стоимости', 'Значение (масса)',
       'Единица объема', 'Дополнительная единица измерения (ДЭИ)',
       'ДЭИ, описание', 'Значение (стоимость) - ДЭИ', 'europe_non_eu', 'asia',
       'america', 'middle_east', 'eu_27', 'nato', 'unfriendly', 'friendly',
       'brics', 'sco', 'cis', 'eaeu', 'africa', 'oceania'],
      dtype='object')

In [16]:
eu_med = eu_med.groupby(['Отчетный период', 'Страна-партнер', 'Направление',
       'Код товара (2 знака)', 'Код товара (4 знака)', 'Единицы стоимости',
       'Единица объема', 'europe_non_eu', 'asia',
       'america', 'middle_east', 'eu_27', 'nato', 'unfriendly', 'friendly',
       'brics', 'sco', 'cis', 'eaeu', 'africa', 'oceania'], as_index=False)[['Значение (стоимость)', 'Значение (масса)']].sum()
eu_med = eu_med[eu_med['Код товара (4 знака)'].isin(['9018', '9019', '9020', '9021', '9022', '9025', '9027', '9030', '9031'])]
eu_med = eu_med[eu_med['Направление'] == 'Импорт']
eu_med

,Отчетный период,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Единицы стоимости,Единица объема,europe_non_eu,asia,america,...,unfriendly,friendly,brics,sco,cis,eaeu,africa,oceania,Значение (стоимость),Значение (масса)
537,2019-01-01,Austria,Импорт,90,9018,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,3.419788e+05,3315.0
538,2019-01-01,Austria,Импорт,90,9021,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,2.525504e+05,655.0
539,2019-01-01,Austria,Импорт,90,9022,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,2.842393e+04,14.0
542,2019-01-01,Austria,Импорт,90,9025,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,3.857517e+03,23.0
544,2019-01-01,Austria,Импорт,90,9027,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,1.023569e+06,7951.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435973,2025-12-01,Türkiye,Импорт,90,9022,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,5.063068e+05,1282.0
1435976,2025-12-01,Türkiye,Импорт,90,9025,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,1.511539e+05,2218.0
1435978,2025-12-01,Türkiye,Импорт,90,9027,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,8.659100e+05,8192.0
1435981,2025-12-01,Türkiye,Импорт,90,9030,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,5.753305e+04,511.0
1435982,2025-12-01,Türkiye,Импорт,90,9031,USD,килограмм,0,0,0,...,0,1,0,0,0,0,0,0,4.370266e+05,6574.0

In [17]:
eu_med.to_csv('eu_final.csv', index=False)

In [13]:
eu_med.groupby('Страна-партнер', as_index=False)['Значение (стоимость)'].sum().sort_values(by='Значение (стоимость)')

                                       Страна-партнер  Значение (стоимость)
16                                            Iceland          1.317031e+03
3                              Bosnia and Herzegovina          6.986091e+03
26                                    North Macedonia          2.632032e+05
0                                             Albania          3.327062e+05
23                               Moldova, Republic of          6.295902e+05
40                  United Kingdom (Northern Ireland)          7.523611e+05
24                                         Montenegro          1.185072e+06
29                                           Portugal          1.349609e+06
6                                              Cyprus          1.935567e+06
5                                             Croatia          3.338142e+06
30                                            Romania          4.158801e+06
22                                              Malta          8.385727e+06
27  Norway (incl. Svalbard and Jan Mayen 'SJ' -> 1...          9.002728e+06
12                                            Georgia          9.908485e+06
21                                         Luxembourg          1.065173e+07
31                                             Serbia          1.256933e+07
14                                             Greece          1.833005e+07
33                                           Slovenia          2.750485e+07
38                                            Ukraine          4.539474e+07
34        Spain (incl. Canary Islands 'XB' from 1997)          7.447571e+07
35                                             Sweden          7.675517e+07
39                                     United Kingdom          7.680139e+07
32                                           Slovakia          1.092855e+08
17                                     Ireland (Eire)          1.310176e+08
4                                            Bulgaria          1.468103e+08
15                                            Hungary          1.608219e+08
8                                             Denmark          1.708557e+08
7                                             Czechia          2.067643e+08
37                                            Türkiye          2.168052e+08
1                                             Austria          2.580968e+08
10                                            Finland          2.699570e+08
9                                             Estonia          2.898040e+08
19                                             Latvia          2.991865e+08
18              Italy (incl. San Marino 'SM' -> 1993)          8.028989e+08
28                                             Poland          8.229904e+08
20                                          Lithuania          9.663811e+08
36     Switzerland (incl. Liechtenstein 'LI' -> 1994)          9.853925e+08
2             Belgium (incl. Luxembourg 'LU' -> 1998)          1.374713e+09
11  France (incl. Saint Barthélemy 'BL' -> 2012; i...          1.441796e+09
25                                        Netherlands          3.824994e+09
13  Germany (incl. German Democratic Republic 'DD'...          7.686796e+09

In [12]:
eu_med.columns

Index(['Отчетный период', 'Страна-партнер', 'Направление',
       'Код товара (2 знака)', 'Код товара (4 знака)', 'Единицы стоимости',
       'Единица объема', 'europe_non_eu', 'asia', 'america', 'middle_east',
       'eu_27', 'nato', 'unfriendly', 'friendly', 'brics', 'sco', 'cis',
       'eaeu', 'africa', 'oceania', 'Значение (стоимость)',
       'Значение (масса)'],
      dtype='object')

## Индия

Довольно быстрый парсер одного из главных торговых партнеров России. Совершаем POST запросы по скрытому API сразу по всем HS8 кодам, итерируясь по месяцам, годам и направлению (экспорт/импорт).
Ограничения:
1. Один запрос не может содержать больше одного месяца
2. Один запрос не может содержать больше одного года
3. Экспорт и импорт разделены на разные БД

In [7]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="India", params={"years": ["2019", "2020", "2021", "2022", "2023", "2024", "2025"]})
data = parser.parse()
data

Собрираем January 2019 года, exdd:   0%|          | 0/12 [00:06<?, ?it/s]

ValueError: No tables found

## Вьетнам

Недолгий парсер ~ 20 минут. Через Selenium собираем ссылки на pdf файлы с разбивкой ВЭД Вьетнама по странам. Скачиваем файлы и считываем из них нужную информацию. Для некоторвх месяцев файлы не доступны - восстанавливаем через следующий, предыдущий месяцы и совокупный тотал за год к моменту. 
Ограничения:
1. Сложность чтения таблиц из pdf файлов
2. Импорт и экспорт разделены на разные файлы
3. Доступен только помесячный тотал

In [1]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Vietnam", params={"years": ["2025"]})
data = parser.parse()
data

/Users/ivanandreev/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/ivanandreev/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Собираю 1.2025, imports: 100%|██████████| 12/12 [00:37<00:00,  3.09s/it]
Собираю 1.2025, exports: 100%|██████████| 12/12 [00:37<00:00,  3.11s/it]

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-09-01,Вьетнам,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,149499179.0,USD,NaN,NaN,NaN,NaN,NaN
1,2025-09-01,Вьетнам,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,174877241.0,USD,NaN,NaN,NaN,NaN,NaN
2,2025-08-01,Вьетнам,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,195159441.0,USD,NaN,NaN,NaN,NaN,NaN
3,2025-08-01,Вьетнам,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,191654521.0,USD,NaN,NaN,NaN,NaN,NaN
4,2025-07-01,Вьетнам,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,231828711.0,USD,NaN,NaN,NaN,NaN,NaN
5,2025-07-01,Вьетнам,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,214224516.0,USD,NaN,NaN,NaN,NaN,NaN
6,2025-06-01,Вьетнам,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,212470803.0,USD,NaN,NaN,NaN,NaN,NaN
7,2025-06-01,Вьетнам,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,203570908.0,USD,NaN,NaN,NaN,NaN,NaN
8,2025-05-01,Вьетнам,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,257454063.0,USD,NaN,NaN,NaN,NaN,NaN
9,2025-05-01,Вьетнам,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,202576934.0,USD,NaN,NaN,NaN,NaN,NaN
10,2025-04-01,Вьетнам,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,232146626.0,USD,NaN,NaN,NaN,NaN,NaN
11,2025-04-01,Вьетнам,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,228010099.0,USD,NaN,NaN,NaN,NaN,NaN
12,2025-03-01,Вьетнам,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,176510553.0,USD,NaN,NaN,NaN,NaN,NaN
13,2025-03-01,Вьетнам,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,199127536.0,USD,NaN,NaN,NaN,NaN,NaN
14,2025-02-01,Вьетнам,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,194772481.0,USD,NaN,NaN,NaN,NaN,NaN
15,2025-02-01,Вьетнам,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,167247042.0,USD,NaN,NaN,NaN,NaN,NaN
16,2025-01-01,Вьетнам,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,211973691.0,USD,NaN,NaN,NaN,NaN,NaN
17,2025-01-01,Вьетнам,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,195938751.0,USD,NaN,NaN,NaN,NaN,NaN
18,2025-01-01,Вьетнам,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,149149745.0,USD,NaN,NaN,NaN,NaN,NaN
19,2025-01-01,Вьетнам,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,179449276.0,USD,NaN,NaN,NaN,NaN,NaN

## Узбекистан

Быстрый парсер. Через GET запрос по API получаем два JSON файла - экспорт и импорт. Оформляем и приводим к единому виду таблицу. Предусмотрен парсинг Беларуси (подробнее ниже)
Ограничения:
1. Импорт и экспорт разделены на разные БД
2. Доступен только помесячный тотал
3. Доступны данные с 2021-ого года.

In [3]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Uzbekistan", params={"years": ["2025"]})
data = parser.parse()
data

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-09-01,Узбекистан,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,715454400.0,USD,NaN,NaN,NaN,NaN,NaN
1,2025-09-01,Узбекистан,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,374550900.0,USD,NaN,NaN,NaN,NaN,NaN
2,2025-08-01,Узбекистан,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,733056700.0,USD,NaN,NaN,NaN,NaN,NaN
3,2025-08-01,Узбекистан,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,405411700.0,USD,NaN,NaN,NaN,NaN,NaN
4,2025-07-01,Узбекистан,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,720402200.0,USD,NaN,NaN,NaN,NaN,NaN
5,2025-07-01,Узбекистан,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,413858300.0,USD,NaN,NaN,NaN,NaN,NaN
6,2025-06-01,Узбекистан,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,739992800.0,USD,NaN,NaN,NaN,NaN,NaN
7,2025-06-01,Узбекистан,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,453013200.0,USD,NaN,NaN,NaN,NaN,NaN
8,2025-05-01,Узбекистан,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,747074700.0,USD,NaN,NaN,NaN,NaN,NaN
9,2025-05-01,Узбекистан,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,381208300.0,USD,NaN,NaN,NaN,NaN,NaN
10,2025-04-01,Узбекистан,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,795485300.0,USD,NaN,NaN,NaN,NaN,NaN
11,2025-04-01,Узбекистан,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,331118400.0,USD,NaN,NaN,NaN,NaN,NaN
12,2025-03-01,Узбекистан,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,623041800.0,USD,NaN,NaN,NaN,NaN,NaN
13,2025-03-01,Узбекистан,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,337898700.0,USD,NaN,NaN,NaN,NaN,NaN
14,2025-02-01,Узбекистан,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,540506100.0,USD,NaN,NaN,NaN,NaN,NaN
15,2025-02-01,Узбекистан,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,279921700.0,USD,NaN,NaN,NaN,NaN,NaN
16,2025-01-01,Узбекистан,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,531127800.0,USD,NaN,NaN,NaN,NaN,NaN
17,2025-01-01,Узбекистан,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,267935400.0,USD,NaN,NaN,NaN,NaN,NaN

## Армения

Быстрый парсер. Обращаемся GET запросом и забираем таблицу с помощью BeautifulSoup. Предусмотрен парсинг Беларуси (подробнее ниже).
Ограничения:
1. Доступен только помесячный тотал

In [5]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Armenia", params={"years": ["2025"]})
data = parser.parse()
data

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-09-01,Армения,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,212846000.0,USD,NaN,NaN,NaN,NaN,NaN
1,2025-09-01,Армения,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,258510100.0,USD,NaN,NaN,NaN,NaN,NaN
2,2025-08-01,Армения,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,276262100.0,USD,NaN,NaN,NaN,NaN,NaN
3,2025-08-01,Армения,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,252929000.0,USD,NaN,NaN,NaN,NaN,NaN
4,2025-07-01,Армения,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,335454900.0,USD,NaN,NaN,NaN,NaN,NaN
5,2025-07-01,Армения,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,278761600.0,USD,NaN,NaN,NaN,NaN,NaN
6,2025-06-01,Армения,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,358040800.0,USD,NaN,NaN,NaN,NaN,NaN
7,2025-06-01,Армения,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,251866400.0,USD,NaN,NaN,NaN,NaN,NaN
8,2025-05-01,Армения,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,390076700.0,USD,NaN,NaN,NaN,NaN,NaN
9,2025-05-01,Армения,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,195733900.0,USD,NaN,NaN,NaN,NaN,NaN
10,2025-04-01,Армения,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,468551500.0,USD,NaN,NaN,NaN,NaN,NaN
11,2025-04-01,Армения,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,197589000.0,USD,NaN,NaN,NaN,NaN,NaN
12,2025-03-01,Армения,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,391236300.0,USD,NaN,NaN,NaN,NaN,NaN
13,2025-03-01,Армения,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,232842900.0,USD,NaN,NaN,NaN,NaN,NaN
14,2025-02-01,Армения,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,243855200.0,USD,NaN,NaN,NaN,NaN,NaN
15,2025-02-01,Армения,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,235325400.0,USD,NaN,NaN,NaN,NaN,NaN
16,2025-01-01,Армения,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,315601000.0,USD,NaN,NaN,NaN,NaN,NaN
17,2025-01-01,Армения,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,204341500.0,USD,NaN,NaN,NaN,NaN,NaN

## Таджикистан

Быстрый парсер. Скачиваем в отдельную директорию RAR архивы по годам, открываем и собираем данные с детализацией по товарам (HS6)по России или Беларуси.
Ограничения:
1. Разные названия файлов, таблиц, листов Excel - скорее всего придется часто дорабатывать парсер, чтобы открывать нужные листы и файлы.
2. Разбивка по кварталам, а не месяцам. Пока что суммы делим на три. Позже можно реализовать более уиное разделение на основе исторических данных.

In [3]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Tadjikistan", params={"years": ["2025"]})
data = parser.parse()
data

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
1,2025-06-01,Таджикистан,Россия,Импорт,01,0101,010129,NaN,NaN,798.666667,USD,426.666667,килограмм,1.000000,ШТ,NaN
2,2025-06-01,Таджикистан,Россия,Импорт,01,0102,010221,NaN,NaN,70353.000000,USD,47938.333333,килограмм,95.000000,ШТ,NaN
4,2025-06-01,Таджикистан,Россия,Импорт,01,0102,010229,NaN,NaN,929803.333333,USD,639180.333333,килограмм,1769.000000,ШТ,NaN
5,2025-06-01,Таджикистан,Россия,Импорт,01,0102,010239,NaN,NaN,6283.333333,USD,4833.333333,килограмм,11.666667,ШТ,NaN
6,2025-06-01,Таджикистан,Россия,Импорт,01,0102,010290,NaN,NaN,5333.333333,USD,5333.333333,килограмм,11.000000,ШТ,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7927,2025-01-01,Таджикистан,Россия,Экспорт,74,7404,740400,NaN,NaN,277479.000000,USD,29333.333333,килограмм,0.000000,КГ,NaN
7928,2025-01-01,Таджикистан,Россия,Экспорт,83,8311,831110,NaN,NaN,92320.000000,USD,34636.666667,килограмм,0.000000,КГ,NaN
7929,2025-01-01,Таджикистан,Россия,Экспорт,84,8422,842230,NaN,NaN,34609.000000,USD,3905.000000,килограмм,0.333333,ШТ,NaN
7930,2025-01-01,Таджикистан,Россия,Экспорт,84,8474,847490,NaN,NaN,22555.000000,USD,28820.000000,килограмм,0.000000,КГ,NaN
7931,2025-01-01,Таджикистан,Россия,Экспорт,87,8703,870323,NaN,NaN,24340.666667,USD,1286.666667,килограмм,0.666667,ШТ,NaN

## Киргизия

Быстрый парсер. Скачиваем XLSX файлы и собираем нужную информацию с детализацией по HS4. Поддержка парсинга Беларуси (подробнее ниже).
Ограничения:
1. Агрегация по годам - пока что делим поровну на 12 месяцев.

In [1]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Kyrgyzstan", params={"years": ["2025"]})
data = parser.parse()
data

/Users/ivanandreev/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/ivanandreev/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-09-01,Киргизия,Россия,Импорт,01,0101,NaN,NaN,NaN,166683.222222,USD,NaN,NaN,261.777778,штук,NaN
1,2025-09-01,Киргизия,Россия,Импорт,01,0102,NaN,NaN,NaN,402886.111111,USD,NaN,NaN,1480.222222,штук,NaN
2,2025-09-01,Киргизия,Россия,Импорт,01,0105,NaN,NaN,NaN,83252.333333,USD,NaN,NaN,100784.444444,штук,NaN
3,2025-09-01,Киргизия,Россия,Импорт,02,0202,NaN,NaN,NaN,766.555556,USD,NaN,NaN,0.166667,тонн,NaN
4,2025-09-01,Киргизия,Россия,Импорт,02,0203,NaN,NaN,NaN,96025.888889,USD,NaN,NaN,37.188889,тонн,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14134,2025-01-01,Киргизия,Россия,Экспорт,96,9613,NaN,NaN,NaN,207.555556,USD,NaN,NaN,0.011111,тонн,NaN
14135,2025-01-01,Киргизия,Россия,Экспорт,96,9615,NaN,NaN,NaN,56.777778,USD,NaN,NaN,0.011111,тонн,NaN
14136,2025-01-01,Киргизия,Россия,Экспорт,96,9617,NaN,NaN,NaN,34573.111111,USD,NaN,NaN,2.200000,тонн,NaN
14137,2025-01-01,Киргизия,Россия,Экспорт,96,9619,NaN,NaN,NaN,6925.000000,USD,NaN,NaN,1.722222,тонн,NaN
14138,2025-01-01,Киргизия,Россия,Экспорт,96,9620,NaN,NaN,NaN,9127.666667,USD,NaN,NaN,0.033333,тонн,NaN

## Азербайджан

Быстрый пасрер. Собираем RAR архивы со статистическими бюллетенями, собираем нужную информацию поквартально с детализацией по HS4 из pdf файлов.
Ограничения:
1. Сложная структура PDF файлов - приходится прописывать множество исключений и вспомогательных функций, чтобы таблица читалась качественно.
2. Поквартальное разбиение - пока что делим на три месяца.
3. Большая задержка.

In [2]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Azerbaijan", params={"years": ["2025"]})
data = parser.parse()
data

Собираю 2025 год: 100%|██████████| 1/1 [00:19<00:00, 19.18s/it]

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-06-01,Азербайджан,Россия,Импорт,01,0101,NaN,NaN,NaN,2.933333e+03,USD,2.333333e+00,əd,NaN,-,NaN
1,2025-06-01,Азербайджан,Россия,Импорт,01,0102,NaN,NaN,NaN,5.014833e+06,USD,5.927333e+03,əd,NaN,-,NaN
2,2025-06-01,Азербайджан,Россия,Импорт,01,0104,NaN,NaN,NaN,2.369300e+06,USD,1.977100e+04,əd,NaN,-,NaN
3,2025-06-01,Азербайджан,Россия,Импорт,01,0105,NaN,NaN,NaN,4.568667e+05,USD,6.208800e+04,əd,NaN,-,NaN
4,2025-06-01,Азербайджан,Россия,Импорт,01,0106,NaN,NaN,NaN,8.833333e+03,USD,6.588833e+06,əd,NaN,-,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4882,2025-01-01,Азербайджан,Россия,Экспорт,94,9405,NaN,NaN,NaN,1.000000e+02,USD,6.466667e+01,kq,NaN,-,NaN
4883,2025-01-01,Азербайджан,Россия,Экспорт,94,9406,NaN,NaN,NaN,1.800000e+03,USD,2.300000e+02,kq,NaN,-,NaN
4884,2025-01-01,Азербайджан,Россия,Экспорт,95,9504,NaN,NaN,NaN,3.333333e+01,USD,2.200000e+01,əd,NaN,-,NaN
4885,2025-01-01,Азербайджан,Россия,Экспорт,96,9616,NaN,NaN,NaN,1.533333e+03,USD,1.520000e+03,kq,NaN,-,NaN
4886,2025-01-01,Азербайджан,Россия,Экспорт,97,9701,NaN,NaN,NaN,2.333333e+02,USD,1.333333e+00,əd,NaN,-,NaN

## СНГ

Вспомогательный класс для парсинга Беларуси (подробнее ниже). 

ВАЖНО!!!
Включает в себя Казахстан, Украину и Молдову - избегайте дублирования, если используете данный класс для получения зеркальной статистики России.

In [ ]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="CIS", params={"years": ["2025"], "belarus": True})
data = parser.parse()
data

/Users/ivanandreev/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/ivanandreev/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

1. Парсим Молдову и Украину

Собрано HS6 (батчей по 50 шт), flow=1: 100%|██████████| 112/112 [01:50<00:00,  1.01it/s]
Собрано HS6 (батчей по 50 шт), flow=2: 100%|██████████| 112/112 [01:49<00:00,  1.03it/s]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.
2. Парсим Казахстан

Парсим 2021 год: 100%|██████████| 5/5 [01:19<00:00, 15.98s/it]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.
3. Парсим Узбекистан
4. Парсим Армению
5. Парсим Таджикистан
6. Парсим Киргизию
7. Парсим Азербайджан

Собираю 2021 год:   0%|          | 0/5 [00:00<?, ?it/s]bsdtar: Error opening archive: Failed to open './data/files/Bulleten-2021/Bulleten_2021_IV RUB.rar'
Собираю 2023 год:  40%|████      | 2/5 [01:23<02:06, 42.33s/it]bsdtar: Error opening archive: Failed to open './data/files/Billuten 2023_illik/Bulleten_2023_IV rub/Bulleten 2023_IV rub.rar'
Собираю 2025 год: 100%|██████████| 5/5 [03:08<00:00, 37.70s/it]

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-05-01,"Moldova, Republic of",Беларусь,Импорт,03,0305,030539,NaN,NaN,48051.299228,USD,2524.000000,килограмм,NaN,NaN,NaN
1,2025-05-01,"Moldova, Republic of",Беларусь,Импорт,03,0305,030541,NaN,NaN,1560.810133,USD,64.000000,килограмм,NaN,NaN,NaN
2,2025-05-01,"Moldova, Republic of",Беларусь,Импорт,03,0305,030543,NaN,NaN,21977.650191,USD,1215.000000,килограмм,NaN,NaN,NaN
3,2025-05-01,"Moldova, Republic of",Беларусь,Импорт,04,0401,040120,NaN,NaN,70430.429482,USD,82910.000000,килограмм,NaN,NaN,NaN
4,2025-05-01,"Moldova, Republic of",Беларусь,Импорт,04,0401,040140,NaN,NaN,1888.986252,USD,1080.000000,килограмм,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12166,2021-01-01,Азербайджан,Беларусь,Экспорт,58,5802,NaN,NaN,NaN,1900.000000,USD,949.000000,m2,NaN,-,NaN
12167,2021-01-01,Азербайджан,Беларусь,Экспорт,63,6302,NaN,NaN,NaN,3866.666667,USD,688.233333,kq,NaN,-,NaN
12168,2021-01-01,Азербайджан,Беларусь,Экспорт,73,7311,NaN,NaN,NaN,3800.000000,USD,16.000000,kq,NaN,-,NaN
12169,2021-01-01,Азербайджан,Беларусь,Экспорт,84,8411,NaN,NaN,NaN,8666.666667,USD,0.666667,əd,NaN,-,NaN
12170,2021-01-01,Азербайджан,Беларусь,Экспорт,84,8420,NaN,NaN,NaN,3866.666667,USD,0.333333,əd,NaN,-,NaN

## Беларусь

Беларусь - одна из важнейших стран-партнеров России. Однако Беларусь публикует лишь помесячные суммы экспорта/импорта,агрегированные по СНГ. Поэтому чтобы достать торговлю РФ и Беларуси, мы сначала вычислим месячные суммы для всех стран СНГ с Беларусью, а потом возьмем разницу. Единственной проблемой является Туркмения, по которой нет вообще никакой статистики. Будем считать, что торговля Туркмении и Беларуси ничтожно мала.

In [2]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="Belarus", params={"years": ["2025"]})
data = parser.parse()
data

/Users/ivanandreev/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/ivanandreev/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Собираю 2025 год: 100%|██████████| 1/1 [00:01<00:00,  1.24s/it]

Переходим к парсингу торговли Беларуси с СНГ
1. Парсим Молдову и Украину

Собрано HS6 (батчей по 50 шт), flow=1: 100%|██████████| 155/155 [00:50<00:00,  3.08it/s]
Собрано HS6 (батчей по 50 шт), flow=2: 100%|██████████| 155/155 [00:50<00:00,  3.08it/s]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.
2. Парсим Казахстан

Парсим 2025 год:  20%|██        | 1/5 [01:17<05:09, 77.27s/it]

Парсинг успешно завершен. Перехожу к составлению и оформлению итоговой таблицы.
3. Парсим Узбекистан
4. Парсим Армению
5. Парсим Таджикистан
6. Парсим Киргизию
7. Парсим Азербайджан

Собираю 2025 год: 100%|██████████| 1/1 [00:20<00:00, 20.28s/it]

Вычленим остаток

,Отчетный период,Исходная страна,Страна-партнер,Направление,Код товара (2 знака),Код товара (4 знака),Код товара (6 знаков),Код товара (8 знаков),Код товара (10 знаков),Значение (стоимость),Единицы стоимости,Значение (масса),Единица объема,Дополнительная единица измерения (ДЭИ),"ДЭИ, описание",Значение (стоимость) - ДЭИ
0,2025-06-01,Беларусь,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,2.066838e+09,USD,NaN,NaN,NaN,NaN,NaN
1,2025-06-01,Беларусь,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,2.531346e+09,USD,NaN,NaN,NaN,NaN,NaN
2,2025-05-01,Беларусь,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,1.835680e+09,USD,NaN,NaN,NaN,NaN,NaN
3,2025-05-01,Беларусь,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,2.384964e+09,USD,NaN,NaN,NaN,NaN,NaN
4,2025-04-01,Беларусь,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,2.007888e+09,USD,NaN,NaN,NaN,NaN,NaN
5,2025-04-01,Беларусь,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,2.333185e+09,USD,NaN,NaN,NaN,NaN,NaN
6,2025-03-01,Беларусь,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,2.217407e+09,USD,NaN,NaN,NaN,NaN,NaN
7,2025-03-01,Беларусь,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,2.405276e+09,USD,NaN,NaN,NaN,NaN,NaN
8,2025-02-01,Беларусь,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,1.924995e+09,USD,NaN,NaN,NaN,NaN,NaN
9,2025-02-01,Беларусь,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,2.084706e+09,USD,NaN,NaN,NaN,NaN,NaN
10,2025-01-01,Беларусь,Россия,Импорт,NaN,NaN,NaN,NaN,NaN,1.674380e+09,USD,NaN,NaN,NaN,NaN,NaN
11,2025-01-01,Беларусь,Россия,Экспорт,NaN,NaN,NaN,NaN,NaN,1.847754e+09,USD,NaN,NaN,NaN,NaN,NaN

## Китай

Самый сложный и долгий парсер. Перебираем HS8 и года. Отправляем пост запросы в Selenium с помощью JS. Один год парсится приблизительно 4-5 часов. В самом начале запуска необходимо вручную ввести один код и решить каптчу (паззл со слайдером). Тогда дальнейшие запросы будут срабатывать.
Ограничения:
1. Длительное время запросов
2. Каптча

Я заметил, что картинки каптчи повторяются. Кажется, что возможно собрать датасет и разметить его количеством пикселей, на которые надо передвинуть парсер. Тогда с помощью ActionChains можно будет автоматизировать решение каптчи.

In [8]:
from RussianForeignTradeParser_1 import RussianForeignTradeParser_1

parser = RussianForeignTradeParser_1(country="China", params={"version_main": 146, "years": ["2025"]})
data = parser.parse()
data

/Users/ivanandreev/Desktop/trade_project-main/scrapers/China.py:186: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd.read_csv("./data/Commodity.csv", encoding="latin1", sep='","')['"CODES'].str[:8]

Пожалуйста, выберите в первом селекторе 'Select Commodity' и в появившееся поле введите '01'. Нажмите кнопку 'Enqueyri' и решите каптчу. По завершении введите в консоль любое число для начала парсинга

Собрано HS8 (батчей по 16 шт.), 0, 2025:   0%|          | 0/560 [00:30<?, ?it/s]

KeyboardInterrupt: